#!/usr/bin/env bash

set -e

# We don't want `less` to open for `git grep` results in the below scripts when running locally.
export GIT_PAGER=cat

./scripts/enforce-issue-number-for-todos
./scripts/enforce-newline-at-eof

./scripts/prohibit-tab-character
./scripts/prohibit-trailing-whitespace
