# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1.4.0
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Run pre-compile checks
        run: ./scripts/run-pre-build-checks

      - name: Build with Gradle
        run: gradle build dokkaHtml

      - name: Update gh-pages
        run: |
          if [ $GITHUB_REF = "refs/heads/master" ]; then
             git config --global user.email "$(git log -1 --format=%ae)"
             git config --global user.name "$(git log -1 --format=%an)"
             git subtree add --prefix=our-site origin gh-pages
             rm -r our-site/*
             cp -r  build/dokka/html/* our-site
             git add our-site
             git commit -m "$(git log -1 --pretty=%B)"
             git subtree push --prefix=our-site origin gh-pages
          fi
